language: cpp

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    # - { os: linux, env: PYTHON_VERSION=3.5 }

sudo: True

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - gfortran
    - clang
    - libz-dev
    - libbz2-dev
    - libblas-dev
    - liblapack-dev
    - libarpack2-dev
    - libnetcdf-dev

install:
    - sudo apt-get install libfftw3-3
    
script:
    - source devtools/travis-ci/setup_env.sh
    - python setup.py install
    - export AMBERHOME=`python -c 'import sys; print(sys.prefix)'`
    - py.test -vs jamber/

after_success:
    - echo "hello"

notifications:
  email: false
